export const SET_USER = 'SET_USER';

export const UPDATE_CATEGORY_FORM_FIELD = 'UPDATE_CATEGORY_FORM_FIELD';
export const RESET_CATEOGRY = 'RESET_CATEGORY';

export const SET_ACTIVE_DATE = 'SET_ACTIVE_DATE';

export const GET_CATEGORIES = 'GET_CATEGORIES';

export const UPDATE_TRANSACTION_FIELD = 'UPDATE_TRANSACTION_FIELD';
export const RESET_TRANSACTION = 'RESET_TRANSACTION';
export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const GET_TRANSACTION_GROUPS = 'GET_TRANSACTION_GROUPS';
